### ISSUE TITLE
Block out all scenes

### ISSUE THREAD

**Issue by pwc** [drobgrog/melsim#31]
## TODO
- [x] Add home music
- [x] Add Park background
- [x] Add Park music
- [x] Add Park colliders
- [x] Add shops background
- [x] Add shops colliders
